FROM node:10-alpine
# Install Python.
# RUN \
#   apt-get update && \
#   apt-get install -y python3 python3-dev python-pip python-virtualenv && \
#   pip3 install --upgrade pip setuptools && \
#   rm -rf /var/lib/apt/lists/*
RUN apk update && apk upgrade \
    && echo "|--> Install Main Packages" \
    && apk add --no-cache tini curl ca-certificates python3 py3-numpy \
        py3-numpy-f2py freetype jpeg libpng libstdc++ \
        libgomp graphviz font-noto openssl && \
    python3 -m ensurepip && \
    rm -r /usr/lib/python*/ensurepip && \
    pip3 --no-cache-dir install --upgrade pip setuptools wheel && \
    if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi && \
    rm -r /root/.cache \
## Dev dependencies and others stuffs...
    && echo "|--> Install build dependencies" \
    && apk add --no-cache -U --virtual=.build-deps \
        build-base linux-headers python3-dev cython-dev py-setuptools py3-setuptools git \
        cmake jpeg-dev libffi-dev gfortran openblas-dev \
        py-numpy-dev freetype-dev libpng-dev libexecinfo-dev \
    && echo "|--> Install Python packages" \
    && pip install -U --no-cache-dir pyyaml pymkl pillow zmq \
## Cleaning
    && echo "|--> 1st Cleaning" \
    && rm -rf /root/.cache \
    && rm -rf /root/.[acpw]* \
    && rm -rf /var/cache/apk/* \
    && find /usr/lib/python3.6 -name __pycache__ | xargs rm -r \
# Install PyTorch
    && apk update && apk upgrade \
    && echo "|--> Get LibPyYAML" \
    && git clone https://github.com/yaml/libyaml libyaml \
    && cd libyaml \
    && ./bootstrap \
    && ./configure \
    && make \
    && make install \
    && echo "|--> Clone PyTorch" \
    && git clone --recursive https://github.com/pytorch/pytorch \
    && echo "|--> Install PyTorch" \
    && cd pytorch && python setup.py install \
    && echo "|--> Clone Torch Vision" \
    && git clone --recursive https://github.com/pytorch/vision \
    && echo "|--> Install Torch Vision" \
    && cd vision && python setup.py install \
## Cleaning
    && echo "|--> 2nd Cleaning" \
    && rm -rf /libyaml \
    && rm -rf /pytorch \
    && rm -rf /root/.cache \
    && rm -rf /var/cache/apk/* \
    && apk del .build-deps \
    && find /usr/lib/python3.6 -name __pycache__ | xargs rm -r \
    && rm -rf /root/.[acpw]*
    
# Create working directory
WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 8888

CMD ["npm", "start"]